version: '3.8'

services:
  taskmanagement-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://docker-file-db-1:5432/definex
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - docker-file_default

networks:
  docker-file_default:
    external: true