spring:
 application:
  name: taskmanagement

 datasource:
  url: jdbc:postgresql://postgres-service:5432/TASKMANAGEMENT
  username: POSTGRES
  password: 12345
  driver-class-name: org.postgresql.Driver

 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: create-drop
  show-sql: true
 servlet:
  multipart:
   max-file-size: 10MB
   max-request-size: 10MB
jwt:
 secret: E3F2B87DF10D3A43257E4D68D50D97E810556C1D24C852E174875CE3194E1C16
 expiration: 3600000

management:
 endpoints:
  web:
   exposure:
    include: "health,info"
 endpoint:
  health:
   show-details: always
 security:
  enabled: false  # Bu satırı ekle

file:
 upload-dir: C:/Users/caner/OneDrive/Belgeler/Taskmanagement

security:
 auth:
  public-endpoints: "/api/auth/**, /actuator/**, /actuator/health/**, /actuator/health/readiness, /actuator/health/liveness"
  team-leader-endpoints: "/api/departments/**"